variable "platform" {
  type = object({
    tenant_id       = string
    subscription_id = string
    location        = string
    state_rg        = string
    state_storage   = string
    state_container = string
    keyvault_name   = string
  })
  description = "Platform seed values from _platform.auto.tfvars (generated by statefiles-generator). Used to read platform state via the read-state helper module."
}

variable "basics" {
  type = object({
    base_name   = string
    environment = string
  })
  description = "Project basics from _basics.tf (generated by statefiles-generator)."
}

variable "image_name" {
  type        = string
  description = "Full image reference including registry and tag (set by CI from build output)."
}

variable "diff_path" {
  type        = string
  default     = "/mnt/repo/app/data/sample.diff"
}

variable "mount_path" {
  type        = string
  default     = "/mnt/repo"
}

variable "min_replicas" {
  type    = number
  default = 1
}

variable "max_replicas" {
  type    = number
  default = 3
}

variable "cpu" {
  type    = number
  default = 0.25
}

variable "memory" {
  type    = string
  default = "0.5Gi"
}

variable "custom_domain" {
  type        = string
  default     = "nupla.info"
  description = "Custom hostname for the Container App. Set to null to skip Cloudflare DNS + hostname binding."
}

variable "cloudflare_token_secret_name" {
  type    = string
  default = "nupla-cloudflare-token"
}

variable "cloudflare_zone_id_secret_name" {
  type    = string
  default = "nupla-cloudflare-zone-id"
}
